AWSTemplateFormatVersion: 2010-09-09
Description: Creates a new role to allow an administrator account to enable and manage SecurityHub.

Parameters:
  AdministratorAccountId:
    Type: String
    Description: AWS Account Id of the administrator account (the account in which will recieve SecurityHub findings from member accounts).
    MaxLength: 12
    MinLength: 12
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ManageSecurityHub
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref AdministratorAccountId
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: ManageSecurityHub
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "iam:CreateServiceLinkedRole"
                Resource: "*"
                Condition:
                  StringLike:
                    "iam:AWSServiceName": 
                      - "securityhub.amazonaws.com"
                      - "config.amazonaws.com"
              - Effect: Allow
                Action: "securityhub:*"
                Resource: "*"
              - Effect: Allow
                Action: 
                  - config:DescribeConfigurationRecorders
                  - config:DescribeDeliveryChannels
                  - config:DescribeConfigurationRecorderStatus
                  - config:DeleteConfigurationRecorder
                  - config:DeleteDeliveryChannel
                  - config:PutConfigurationRecorder
                  - config:PutDeliveryChannel
                  - config:StartConfigurationRecorder
                Resource: "*"
              - Effect: "Allow"
                Action: "iam:PassRole"
                Resource: "arn:aws:iam::*:role/aws-service-role/config.amazonaws.com/AWSServiceRoleForConfig"
              - Effect: "Allow"
                Action:
                  - "s3:CreateBucket"
                  - "s3:PutBucketPolicy"
                  - "s3:ListBucket"
                Resource: "arn:aws:s3:::config-bucket-*"

